### ISSUE TITLE
s_ref assertion in geometry

### ISSUE THREAD

**Issue by chiefenne** [peterdsharpe/AeroSandbox#1]
**Describe the bug**
In geometry.py the attribute s_ref asserts if only one wing is specified.

**Expected behavior**
It seems that the comment is right, but the code does not reflect that.
`if len(self.wings) > 1:  # If there is at least one wing`
should this be:
`if len(self.wings) > 0:  # If there is at least one wing`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Anaconda Python 3.7.x

**Comment by peterdsharpe** [comment]
Oh whoops - great catch! Thank you so much! :)

I've just committed the change - it should make it into the next release, which will come out shortly!
