### ISSUE TITLE
Validation test

### ISSUE THREAD

**Issue by jonititan** [peterdsharpe/AeroSandbox#11]
**Is your feature request related to a problem? Please describe.**
What is your opinion on including a validation test case?
That way solver accuracy can be displayed and tests can be added to cover new features as they are added.

**Describe the solution you'd like**
I will write an example next week for PR if you will consider.
I will also include an airfoil file load method as listed in task https://github.com/peterdsharpe/AeroSandbox/projects/2#card-23370502

**Describe alternatives you've considered**

**Additional context**

**Comment by peterdsharpe** [comment]
Hey @jonititan,

A validation case is a great idea! That's kind of what I was hoping that /examples/vlm3_conventional would be, but there's probably a better way to implement it.

And thank you so much for implementing an airfoil file load method!

Please let me know if there's anything I can help you with!

**Comment by jonititan** [comment]
Ok well I don't have the book you reference but between the Cranfield library and the internet I’m sure we can find a few validation cases.
Creating a file load method makes it easier to add new test cases which is why I linked the two.

**Comment by aqreed** [comment]
Hello, there is an interesting test case that I am using for my own VLM code in "Aerodynamics for Engineers" by John J. Bertin and Michael L. Smith. You can find it in Ch. 7 "Incompressible Flow about Wings of Finite Span", example 7.2.

Hope this is useful to you.
