### ISSUE TITLE
AVL command execution gives problems related with subprocess.Popen

### ISSUE THREAD

**Issue by DavidRamosArchilla** [peterdsharpe/AeroSandbox#142]
## Bug Description / Observed Behavior
There is a bug in the current implementation of the AVL command execution. The command is being passed as a single string to subprocess.Popen, which can lead to issues, at least in my case, and this makes AVL not work.

## Steps to Reproduce
After adding avl to the path, when an example similar to the one on the documentation is run (https://aerosandbox.readthedocs.io/en/master/autoapi/aerosandbox/aerodynamics/aero_3D/avl/index.html#aerosandbox.aerodynamics.aero_3D.avl.AVL) an error is thrown:   
```python
import aerosandbox as asb

airplane = asb.Airplane(
    name="Sandbox",
    xyz_ref=[0, 0, 0],
    wings=[
        asb.Wing(
            name="Main Wing",
            xyz_le=[0, 0, 0],
            symmetric=True,
            xsecs=[
                asb.WingXSec(
                    xyz_le=[0, 0, 0],
                    chord=1,
                    twist=0,
                    airfoil=asb.Airfoil(name="naca0012")
                ),
                asb.WingXSec(
                    xyz_le=[0, 1, 0],
                    chord=1,
                    twist=0,
                    airfoil=asb.Airfoil(name="naca0012")
                )
            ]
        )
    ]
)

avl = asb.AVL(
    airplane=airplane,
    op_point=asb.OperatingPoint(
        atmosphere=asb.Atmosphere(altitude=0),
        velocity=10,
        alpha=5,
        beta=0,
    ),
    verbose=True,
    working_directory='.',
    timeout=None
)
analysis = avl.run()
```
The error message is `FileNotFoundError: [Errno 2] No such file or directory: 'avl airplane.avl'`. This indicates that the system recognizes "avl airplane.avl" as a single command and not as a command (avl) and its argument (airblane.avl). 
In the documentation of python's subprocess.Popen they say at the end of the constructor docs: "Unless otherwise stated, it is recommended to pass args as a sequence." and it might be the source of the problem.

## Expected Behavior
This should not give an error.

## System Information

* Operating System: Ubuntu 24.04.1 LTS
* Python Version: 3.12.3
* AeroSandbox Version:  4.2.6

## Other Information
The error seems to be on the line 247 from `aerosandbox/aerodynamics/aero_3D/avl.py`: 

```python
command = f"{self.avl_command} {airplane_file}"
```

Changing this line for this one should fix the problem: 
```python
command = [self.avl_command, airplane_file]
```

I am opening a pull request with the changes.

**Comment by peterdsharpe** [comment]
#143 merged
