### ISSUE TITLE
Small bug and quick fix

### ISSUE THREAD

**Issue by silverdonkey** [peterdsharpe/AeroSandbox#147]
## Bug Description / Observed Behavior
Analysis brake when method 'fig.draw()' is called (backend='plotly', haven't testet with other backends):

Cause: There is a missing  ',' between the parameters of the draw() method: colorbar_title=colorbar_label**show_kwargs,

Applies to following analysis types:

1. LiftingLine
[aerosandbox/aerodynamics/aero_3D/lifting_line.py](https://github.com/peterdsharpe/AeroSandbox/blob/b14400c02c711646e9621279b80e5ff7470ec1ad/aerosandbox/aerodynamics/aero_3D/lifting_line.py#L1156), line 1156, in draw
    colorbar_title=colorbar_label**show_kwargs,

2. NonlinearLiftingLine
[aerosandbox/aerodynamics/aero_3D/nonlinear_lifting_line.py](https://github.com/peterdsharpe/AeroSandbox/blob/b14400c02c711646e9621279b80e5ff7470ec1ad/aerosandbox/aerodynamics/aero_3D/nonlinear_lifting_line.py#L836), line 836, in draw
    colorbar_title=colorbar_label**show_kwargs,

## Quick-Fix
Add the missing  ',' between the params of the draw() method in both files.

Should be: 

```            
return fig.draw(
       show=show,
       colorbar_title=colorbar_label, # add comma here
       **show_kwargs,
)
```

## Steps to Reproduce
Create a simple Aaeroplane, e.g. vanilla and configure and run analysis type LiftingLine or NonlinearLiftingLine with backend='plotly'.

Make sure to call the analysis.draw() method after analysis.run()

## Expected Behavior
Should just work ;)

## System Information

* Operating System: MacOS
* Python Version: 3.13.0
* AeroSandbox Version: 4.2.6

## Other Information
I hope you can simply apply the fixes above without me creating PR.

**Comment by peterdsharpe** [comment]
Oh wow! Great find - thanks for letting me know. I'm wondering if the recent use of the Ruff linter broke this; I'll have to check the Git history.

Fixed on develop, will be merged into master on next release!
