### ISSUE TITLE
VLM3 calculation prints out VLM2

### ISSUE THREAD

**Issue by chiefenne** [peterdsharpe/AeroSandbox#2]
**Describe the bug**
Seems to be a copy/paste typo in aerodynamics.py:
`class vlm3(AeroProblem)` and there in the function `def run(self, verbose=True):`:

It prints:
`if self.verbose: print("Running VLM2 calculation...")`
and
`if self.verbose: print("VLM2 calculation complete!")`

**Expected behavior**
`if self.verbose: print("Running VLM3 calculation...")`
and
`if self.verbose: print("VLM3 calculation complete!")`

**Comment by peterdsharpe** [comment]
Ah! Another good catch! Fixed in the latest commit - thank you so much! :D
