### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by KikeM** [peterdsharpe/AeroSandbox#27]
I've realized you are doing a lot of changes and so forth. 

Have you heard of [Travis CLI](https://travis-ci.org)? They provide free testing with each commit for open source code (like yours!).

Basically we need to set up a `tests` folder where tests are set up. At this stage of rapid development of your code it would suffice to assume what comes out is correct and so basically the expected outcome is the current output. 

In this way, whenever you keep changing stuff you will get emails when you things broke down the way.

Additionally, it allows you to test deploys on different operating systems (as far as I recall) and for different Python versions.

**Comment by peterdsharpe** [comment]
Just got Travis CI set up today, per your suggestion! Woohoo!

I've also implemented proper branching ("master" and "develop"), and Travis will auto-upload to PyPI whenever it sees new commits on "master" (if tests pass)! So cool!
