### ISSUE TITLE
Error Running vlm3_conventional.py

### ISSUE THREAD

**Issue by StepLogic** [peterdsharpe/AeroSandbox#29]
Traceback (most recent call last):
  File "C:/Users/Gyaase Elvis/Anaconda3/envs/cpacscreator/Lib/site-packages/aerosandbox_legacy_v0/examples_legacy_v0/vlm3_conventional.py", line 19, in <module>
    control_surface_hinge_point=0.75 # as chord fraction
TypeError: __init__() got an unexpected keyword argument 'xyz_le'
 
I get the above error when i run the file, any help?

**Comment by peterdsharpe** [comment]
Hey @StepLogic , thanks for the issue ticket!

Successfully reproducing the error over here. Seems like I made a mistake in the imports when doing the version upgrade - try replacing the first line of `vlm3_conventional` as follows:

`from aerosandbox import *` -> `from aerosandbox_legacy_v0 import *`

Sorry about that,
Peter

**Comment by peterdsharpe** [comment]
Other notes: you may find you need to pip-install the `autograd` and `pyvista` packages, if you don't have them already!
