### ISSUE TITLE
Airplane not considering Wing>xsecs>Airfoil: name or coordinates for draw()

### ISSUE THREAD

**Issue by andresakle** [peterdsharpe/AeroSandbox#35]
When drawing a simple *Wing* with only two *xsecs* and each with *airfoil=Airfoil(name="naca0099")* the image is does not respect the airfoil.

**To Reproduce**
```python
import copy
from aerosandbox import *

airplane = Airplane(
    name="Test1",
    x_ref=0,  # CG location
    y_ref=0,  # CG location
    z_ref=0,  # CG location
    wings=[
        Wing(
            name="Main Wing",
            x_le=0,  # Coordinates of the wing's leading edge
            y_le=0,  # Coordinates of the wing's leading edge
            z_le=0,  # Coordinates of the wing's leading edge
            symmetric=True,
            xsecs=[  # The wing's cross ("X") sections
                WingXSec(  # Root
                    x_le=0,  # Coordinates of the XSec's leading edge, relative to the wing's leading edge.
                    y_le=0,  # Coordinates of the XSec's leading edge, relative to the wing's leading edge.
                    z_le=0,  # Coordinates of the XSec's leading edge, relative to the wing's leading edge.
                    chord=0.1,
                    twist=0,  # degrees
                    airfoil=Airfoil(name="naca0099"),
                ),
                WingXSec(  # Mid
                    x_le=0.0,
                    y_le=0.2,
                    z_le=0,
                    chord=0.1,
                    twist=0,
                    airfoil=Airfoil(name="naca0099"),
                )
            ]
        )
    ]
)

# Create solved object
ap = copy.deepcopy(airplane)
ap.draw()
```

**Expected behavior**
Image with a Cross Section corresponding to NACA0099:
<img width="1435" alt="Screen Shot 2020-06-14 at 19 01 06" src="https://user-images.githubusercontent.com/4336497/84607212-a5895600-ae71-11ea-8637-65810723a2cf.png">

**Result not desired**
<img width="962" alt="Screen Shot 2020-06-14 at 19 15 17" src="https://user-images.githubusercontent.com/4336497/84607526-66f49b00-ae73-11ea-8b42-5230151c8211.png">
<img width="833" alt="Screen Shot 2020-06-14 at 19 15 49" src="https://user-images.githubusercontent.com/4336497/84607539-78d63e00-ae73-11ea-854b-ca76db71921a.png">

**Platform (untested elsewhere)**
 - OS: macOS Catalina Version 10.15.5
- Python 3.6.5 with virtualenv==16.5.0 containing:
AeroSandbox==2.2.9
casadi==3.5.1
cycler==0.10.0
dill==0.3.1.1
kiwisolver==1.2.0
matplotlib==3.2.1
multiprocess==0.70.9
numpy==1.18.5
pandas==1.0.4
plotly==4.8.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
retrying==1.3.3
scipy==1.4.1
seaborn==0.10.1
six==1.15.0
tqdm==4.46.1

**Other Info**
Tried using coordinate from *.dat* file for foil without success.

**Comment by peterdsharpe** [comment]
Hi @andresakle,

Thanks for writing in! This is not exactly a bug per say (as it is working as intended for the time being), but it is a missing feature. Your proposal to draw the full 3D airplane geometry (including airfoils) is a great idea - unfortunately, I haven't gotten around to implementing it yet! Hopefully I'll have time to look at this soon (PRs always welcome too)!

Best,
Peter
