### ISSUE TITLE
No force output by panel1

### ISSUE THREAD

**Issue by zjb19900907** [peterdsharpe/AeroSandbox#36]
Hello,
When I test the panel1 program ,I find that the relevant codes related to aero force have been annotated. I tried to activate them again, but there are many problems ,and the results are also not right. Is it posiible to recover the calcuration of force?

**Comment by peterdsharpe** [comment]
Hi @zjb19900907, thanks for the bug report and sorry for the delayed repsonse. `panel1` is a deprecated analysis that was dropped in the AeroSandbox awhile ago (around v1.0.0), so it is no longer supported. Instead, the lifting line and vortex lattice methods are now used for 3D aero analysis.
