### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by jonititan** [peterdsharpe/AeroSandbox#4]
Nice project.
I noticed your note re SI units

> One final point to note: as we're all sensible and civilized human beings here, all inputs and outputs to AeroSandbox are expressed in base metric units (meters, Newtons, kilograms, etc.).

So may I take it that velocity is in m/s?
If I wrote a pull request going through and annotating the docstrings to reflect would that be ok?

**Comment by peterdsharpe** [comment]
Thank you, and I hope the code is helpful to you! :) Yes - velocity is in m/s!

A pull request for annotating docstrings would be greatly appreciated - thank you so much for your contributions!

**Comment by peterdsharpe** [comment]
Hey Jonititan, just wanted to check in and see how this was going!

**Comment by jonititan** [comment]
Hopefully have a chance to get to this tonight or tomorrow.

Also thinking there might be some interesting other bits.

I'll write them up as feature requests perhaps and I can write branches for
them after.

**Comment by peterdsharpe** [comment]
Awesome - thanks so much for your first few pull requests! I merged them, they look great!

By the way, please consider starring the repo if you're interested in it! :)

**Comment by peterdsharpe** [comment]
Just got home and had a chance to look at your "Wild Turkey" example - looks sweet!
