### ISSUE TITLE
pytest is required but not included

### ISSUE THREAD

**Issue by tj-murphy** [peterdsharpe/AeroSandbox#42]
## Steps to Reproduce
Install Aerosandbox
Attempt to run the simple_example.py in the examples directory on this repo
## Expected Behavior
Script running. But it says I don't have pytest. I believe this is from aerosandbox importing Opti, and then opti importing pytest.
## System Information
* Operating System: Ubuntu 20.04.2
* Python Version: 3.8.5
* AeroSandbox Verion: Unknown, but just installed from pip yesterday.

**Comment by Christophe-Foyer** [comment]
I think this has to do with this line in opti.py.

> https://github.com/peterdsharpe/AeroSandbox/blob/3596989924c96b480d8d5103fccfc04e90de45c1/aerosandbox/optimization/opti.py#L4

For now as a quick fix you can just install pytest ('pip install pytest'), but this issue should be corrected as it shouldn't be required.

**Comment by Christophe-Foyer** [comment]
Should be addressed by this hotfix: https://github.com/peterdsharpe/AeroSandbox/pull/43

**Comment by peterdsharpe** [comment]
Hey @tj-murphy, thanks for the bug report!

@Christophe-Foyer is spot on with his find and put together a perfect hotfix - it's been reviewed and merged. Thanks Christophe! :)

Closing this issue; please let us know if import problems continue!
