### ISSUE TITLE
Fuselage with Rectangular Profile

### ISSUE THREAD

**Issue by StepLogic** [peterdsharpe/AeroSandbox#48]
## Additional Context
Hello
I would like to know if it is possible to have fuselages with rectangular profiles
thanks

**Comment by peterdsharpe** [comment]
Hi @StepLogic , thanks for reaching out!

Right now, that is unfortunately not a feature. Feel free to add this if interested; a guide for how to contribute is here: https://github.com/peterdsharpe/AeroSandbox/blob/master/CONTRIBUTING.md

**Comment by StepLogic** [comment]
Thanks
