### ISSUE TITLE
NameError: name 'cas' is not defined

### ISSUE THREAD

**Issue by StepLogic** [peterdsharpe/AeroSandbox#49]
I get  "NameError: name 'cas' is not defined" when I run the lifting line example in test aero3D 

## System Information
* Operating System:Windows 10
* Python Version:3.7
* AeroSandbox Verion:3.0.7

**Comment by peterdsharpe** [comment]
Ah!

Yes, these are tests in progress. (tests not in progress have names that begin with `test_`, and are hence discovered by PyTest.) The LiftingLine analysis still needs to be upgraded to be compatible with ASB v3.0.0+ syntax, so it'll be a few weeks before it's working again.

If needed, a working version of the LiftingLine analysis can be found in the latest AeroSandbox v2 version (installable with `pip install aerosandbox<3`)
