### ISSUE TITLE
Question about outputing airfoil/fuselage

### ISSUE THREAD

**Issue by itisyeetimetoday** [peterdsharpe/AeroSandbox#5]
Nice Project! Exactly what I need for my CS adventure. How do I output a mesh file for 3d printing of the airfoil/fuselage? Thank you

**Comment by peterdsharpe** [comment]
Hey there! Geometry export hasn't been implemented yet - the current idea is that you can do the design and optimization (the difficult part) in AeroSandbox, and then you could do the actual geometry (complete with internal structures, interfaces, etc.) in some external geometry program, such as SolidWorks, Inventor, or OpenVSP.

Hopefully geometry export will be implemented in the future, though it's not the priority right now! Constructing aerospace geometry is typically easier than designing aerospace geometry, so I'm trying to tackle the design part first.

As a personal recommendation, OpenVSP is a good open-source software for aerospace geometry modeling (and I believe it exports directly to .stl files for printing).

**Comment by itisyeetimetoday** [comment]
Hi! I have Autodesk Fusion 360 installed. Is there any way to "recreate" a design in fusion 360? If I have the python script export the wing parameters(xyz_ref, xyz_le, symmetric) and each section's parameters (xyz_le, chord,twist), how would I redesign the airfoil in CAD software.

**Comment by itisyeetimetoday** [comment]
Again, I apologize for my large number of questions. Since we are drawing the airfoils anyway, would it be possible to output each section of each airfoil as a DAT file and then manual

**Comment by cjkarcher** [comment]
CAD is a pretty manual process.  If you don't have rather extensive experience in Autodesk or another CAD program, it would be difficult to generate an airplane from scratch.  OpenVSP really is your best bet as a beginner.  It's relatively user friendly.  http://openvsp.org

**Comment by peterdsharpe** [comment]
Thanks for responding, Cody! :)

Closing this for now, but feel free to reopen if you have any other questions!
