### ISSUE TITLE
Add columns for hinge force coefficients (c.Fx, cFy) in XFoil's Airfoil Polar File

### ISSUE THREAD

**Issue by Dirk07** [peterdsharpe/AeroSandbox#55]
## Description of Proposed Feature

XFoil and XFLR5 are lacking ever since of a complete polar data output of an airfoil, where an airfoils' flap has been specified.
While for this case just the hinge moment coefficient cH has been provided in that file, hinge force coefficients in x- and y-direction were missing through all released versions, although these coefficients are (likewise the hinge moment coefficient) a result of integrating (or summing) the cp-distribution over the flapped panels.
For the sake of completeness, the hinge force coefficients should be added to that file output. This allows also the computation of the flap's pressure point location that may be relevant in subsequent aero-elastic analyses.

## Alternatives I Have Considered

Although it might be possible to write a script, reading the airfoil coordinates and every operations points' cp-distributions to perform these integrations / summations and then add these results to an improved polar data file, I could imagine it would be wiser to patch XFoil directly for various reasons.

## Additional Context

Likewise the hinge moment coefficients, the hinge force coefficients are of interrest in wing conception and preliminary design. While the hinge moment coefficients are a good measure to be accounted in initial sizing of the control system, the hinge force coefficients tell you the load split between main foil and flap and thus serve at least in determining ball parl numbers for subsequent structural wing and flap sizing.

**Comment by peterdsharpe** [comment]
Apologies for the delayed reply, but hinge force coefficients are now reported from `asb.XFoil` when the hinge location is specified: https://github.com/peterdsharpe/AeroSandbox/blob/8ad83aa4e4e40c503884c722143b7730c08089fa/aerosandbox/aerodynamics/aero_2D/xfoil.py#L43
