### ISSUE TITLE
Add Explanation and Conventions on Wing Modelling Method(s)

### ISSUE THREAD

**Issue by Dirk07** [peterdsharpe/AeroSandbox#56]
## Description of Proposed Feature

Wing Modelling may follow various methods, which require explanation and conventions in particular on how large _dihedral_ (i.e. winglets) or large _twist_ (in propeller blade design) and perhaps _blending of kinks_ are handled.
Beside that, aerodynamicists and designers like to keep things simple, thus such methods should be implemented to generate with a minimum of input parameters the required input for the formulation of WingXSec(). It further could also make sense to handle in particular planforms (or at least certain parameters, like the tip-root-chord ratio) as interchangeable objects between different wings.

I.e. just think of a single-kinked leading edge and a straight trailing edge. Consider sweep, dihedral and twist (and any later change of them) and further a flap along the entire half-span starting at x_hinge_root = 0.75 and ending with x_hinge_tip = 0.6. How many sections would you have to specify at least? Ok, imagine further a change in airfoil starting at another location than the leading edge kink or any other new design feature to account for. Imagine further, you want to scale all chords or scale the entire wing, keeping aspect ratio constant. There are quite a lot parameters to watch.

Below a brief summary is provided:

**Method 1:** 
Planform (2D) -> Dihedral and Twist -> 3D LE & TE -> Section Sweep along LE & TE (with constant or variing / interpolated airfoils, if specified)

In this method the planform may again be specified by different input:

- Either the 2D LE & TE are defined, using (unsteady) poly-lines or (multiple) bezier-splines, from which all other planform properties (i.e. projected area, aspect ratio, chord distribution, 25%-chord-line and sweep angle distribution) are derived
- Or the before mentioned vice versa, where any arbitrary XX%-chord-line could be chosen for convenience

**Method 2:**
Freeform, using Bezier Surfaces or NURBS (unconventional, but feasible), whose poles are parametrized and can thus be highly abstracted by partially constraining them to each other.

Although may be not explained straight forward, I hope, this gave some inspiration.

## Alternatives I Have Considered

None.

## Additional Context

None.

**Comment by peterdsharpe** [comment]
Tentatively addressed [here](https://github.com/peterdsharpe/AeroSandbox/blob/master/tutorial/04%20-%20Geometry%20and%20Data%20Structures/01%20-%20AeroSandbox%20Data%20Structures/01%20-%20Basic%20Aircraft%20Geometry.ipynb), work in progress.
