### ISSUE TITLE
Wrong requirements when installing via pip

### ISSUE THREAD

**Issue by hughjward** [peterdsharpe/AeroSandbox#66]
## Bug Description
I believe the requirements file is out of date on PyPi

## Steps to Reproduce
Tried to run tutorial 04 - Geometry and Data Structures/01 - AeroSandbox Data Structures/

ModuleNotFoundError: No module named 'pyvista'

## Expected Behavior
Image of geometry should be created

## System Information

* Operating System:
* Python Version:
* AeroSandbox Verion: AeroSandbox-3.2.6-py3-none-any.whl

## Other Information

when running 'pip show aerosandbox' pyvista is not listed in the requirements

if i install pyvista separately (via pip) the image is created

**Comment by hughjward** [comment]
Ah i didn't know PyPi had this functionality, and I also just read the PyPi project page properly!

Sorry to waste your time! 🙄

**Comment by peterdsharpe** [comment]
No worries!
