### ISSUE TITLE
Tutorial 01 - Vortex Lattice Method is not working

### ISSUE THREAD

**Issue by jannav84** [peterdsharpe/AeroSandbox#77]
Hello, 
there is some issue with tutorial on VLM (AeroSandbox/tutorial/06 - Aerodynamics/01 - AeroSandbox 3D Aerodynamics Tools/01 - Vortex Lattice Method.ipynb)

If I run it, I've got error: TypeError: VortexLatticeMethod.__init__() missing 1 required positional argument: 'opti'
In case I provide argument opti=asb.Opti() I obtain other error: 
TypeError: AeroSandboxObject.__init__() takes 1 positional argument but 3 were given

Could you please help me with solving this issue?

Thank you,
Jan

**Comment by peterdsharpe** [comment]
Hi Jan!

I'm surprised to see this error - that almost seems like it's coming from AeroSandbox v2.x.x syntax (current version is 3.5.2). Could you please confirm the Python version and AeroSandbox version you're using, as well as your OS? To obtain your ASB version:

```python
print(asb.__version__)
```

If not on the latest version, please try updating (`pip install --upgrade aerosandbox[full]`) and, if the issue persists, copy-paste the traceback.

Thanks!
-Peter

**Comment by jannav84** [comment]
Hello Peter,
upgrade to the latest  version did a trick. I had v3.1.0 (even though I installed the ASB two days ago via pip). But now, it is working well!
New version also fixed other issue when I was not able to run code in debug mode, due to some error in numpy package. 

Nevertheless, there is one issue, maybe. If I use "aerosandbox.numpy" in the my old code what is working well using "numpy" I receive error: 
"ind = np.where(yi == ysFi)
TypeError: where() missing 2 required positional arguments: 'value_if_true' and 'value_if_false'"

Is it your intention, or some bug? I read your comments on your implementation of numpy in aerosandbox, that sometimes it might not work properly.

Thank you!
Jan

**Comment by peterdsharpe** [comment]
> upgrade to the latest version did a trick

Yay, glad to hear!

-----

Regarding `aerosandbox.numpy.where` - this is (sort of) intended. `aerosandbox.numpy.where` is intended to support a masking conditional syntax of `np.where(condition, value_if_true, value_if_false)`, which is patterned after the syntax of NumPy's `where` function, [docs here](https://numpy.org/doc/stable/reference/generated/numpy.where.html).

That's a 3-argument `where` function: basically, a [conditional ternary operator](https://en.wikipedia.org/wiki/%3F:), but vectorized.

What you're looking for is the 1-argument version of NumPy's `where` function, which is a little different. [As described in the NumPy docs](https://numpy.org/doc/stable/reference/generated/numpy.where.html), try using the more idiomatic syntax of `np.asarray(condition).nonzero()` for this operation. Note for use with AeroSandbox: this operation is (generally) not differentiable, for AD/optimization purposes.

-----

Re: PyCharm Debugging

Hm! It's a bit tough to debug this without a minimum reproducable example. But it looks like the line that triggers this is `import h5py`, so I might try asking around in the h5py issue board? Before doing so, I'd try updating your NumPy and h5py versions to see if that fixes it.
