### ISSUE TITLE
Question about fuselage 

### ISSUE THREAD

**Issue by itisyeetimetoday** [peterdsharpe/AeroSandbox#8]
Hi, 
Sorry if I am asking too many questions, I'm a confused new user at the moment. How do I add/ import a curved or flat fuselage? Like what if my fuselage is shaped like this: https://imgur.com/a/qw1SXG7?

**Comment by cjkarcher** [comment]
That's a rather unusual fuselage shape.  Again, I'd refer you to my response on #5 in regards to using OpenVSP, that should help you out.  A typical fuselage has a rounded nose and a circular-ish cross section, and unless you have extensive aircraft design experience, I'd strongly recommend sticking with that general design.  I'm going to close this issue and kick further geometry discussion over to #5 .
