### ISSUE TITLE
Fuselage Display

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [peterdsharpe/AeroSandbox#87]
Hi Peter,

Great work! This is an awesome repo and I know it all takes work. I am curious about fuselages. In the examples, there is a definition for a fuselage (i.e. in the glider definition for example) but in the output display it is not shown? Is there a way to display a fuselage easily in the output? Is the fuselage not included in the aerodynamic analysis?

Thanks for your help!

**Comment by peterdsharpe** [comment]
Hey @VallesMarinerisExplorer ,

Apologies for the delayed reply. Fuselages aren't considered in the `asb.VortexLatticeMethod` analysis currently.

@Yashil99 is currently doing some good work on lifting-line-based 3D aero methods that have fuselage influences modeled, e.g., https://github.com/Yashil99/AeroSandbox/blob/master/aerosandbox/aerodynamics/aero_3D/NL_lifting_line.py#L604

This will likely be merged into the main ASB repo relatively soon.
