### ISSUE TITLE
There seems to be a problem with the display of symmetrical wings with dihedral

### ISSUE THREAD

**Issue by Zcaic** [peterdsharpe/AeroSandbox#98]
Hello，
 **problem**: I'm defining a symmetrical wing with dihedral, and I draw it , I found it seems to be a little problem, As shown below
![微信截图_20230721010623](https://github.com/peterdsharpe/AeroSandbox/assets/70070459/4190373f-e58f-47c6-88d0-af43ae671035)
**expect**: What I expect should be as shown in the figure below, 
![屏幕截图 2023-07-21 041856](https://github.com/peterdsharpe/AeroSandbox/assets/70070459/94806996-bfeb-48b9-af64-87557accdfcc)
In aerosandbox, the symmetry of the wing seems to be split, I don't know if this will affect the aerodynamic calculations in aerosandbox.

**Comment by peterdsharpe** [comment]
Hey @Zcaic!

Will respond in more detail later, but tl;dr is that this is intended behavior (required to make numerical optimization of aircraft configurations smooth and well-behaved - for example, in cases where you're optimizing the dihedral angle of a V-tail or optimizing the right fuselage-wing intersection geometry) and has negligible impact on any of AeroSandbox's aerodynamic solvers.

**Comment by Zcaic** [comment]
Thank you very much for your reply, I meet this problem while planning to write an aerosandbox to openvsp interface.

**Comment by Zcaic** [comment]
Thank you for the elaboration, I understand that it is to ensure the smoothness of the dihedral at large angles.
