### ISSUE TITLE
don't use generate_polar_function before AeroBuildup.run()

### ISSUE THREAD

**Issue by Zcaic** [peterdsharpe/AeroSandbox#99]
In aerosandbox new version， when I define airfoil **without calling generate_polar_function**, then I use AreoBuildup to calculate aerodynamic, is there any different from calling  **generate_polar_function**， Or if I don‘t call **generate_polar_function** manually， **AeroBuildup.run()** will call **generate_polar_function** automatically?

**Comment by Zcaic** [comment]
Now I know via read **AeroBuildup** code, I found it will call **get_aero_from_neuralfoil()** for aerofoil, So does this mean that I don't need to call **generate_polar_function()** explicitly?

**Comment by peterdsharpe** [comment]
Hey @Zcaic !

`asb.Airfoil.generate_polars()` is no longer needed when performing `asb.AeroBuildup` analyses. (As you note, `AeroBuildup` now completely bypasses XFoil and instead only uses NeuralFoil. NeuralFoil requires no caching.)

In previous versions of AeroSandbox (v4.0.9 and lower), users had to call `asb.Airfoil.generate_polars()` to build up an XFoil data-table (stored in `asb.Airfoil.xfoil_data`), so that `AeroBuildup` could analyze 2D wing sections. Now, that is no longer needed. :)

**Comment by Zcaic** [comment]
hhh, I'm glad to hear it!
And I modified some code about **Airplane.generate_cadquery_geometry()** function.
Beaceuse when export *.step, I found it miss a leading edge like below:
![before](https://github.com/peterdsharpe/AeroSandbox/assets/70070459/fbc062bf-2009-4872-ae21-b10d61437eb9)

**Comment by peterdsharpe** [comment]
Oh awesome, that looks excellent! Your change also probably improves the fidelity of the STEP representation - one possible geometric inaccuracy of the previous code was if the loft gets "twisted" when sweeping between two adjacent airfoils (e.g., [a hyperboloid from twisting a cylinder loft](https://blender.stackexchange.com/questions/114490/twisted-cylinder-hyperboloid-of-one-sheet)). By adding a leading-edge node into the spline, it constrains any possible twisting, at least at the critical leading-edge point. Nice work!

It would be great to merge your improvements into `Airplane.generate_cadquery_geometry()`. Feel free to submit a pull request (if you want to get GitHub "credit" for your contribution), or I can copy-paste add it for you if that's easier.

**Comment by Zcaic** [comment]
I'm happy that it is useful for aerosandbox. You can copy-paste directly because it is a small change.
